# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='基金代码')),
                ('fund_name', models.CharField(max_length=200, verbose_name='基金名称')),
                ('fund_type', models.CharField(blank=True, max_length=50, verbose_name='基金类型')),
                ('fund_company', models.CharField(blank=True, max_length=100, verbose_name='基金公司')),
                ('established_date', models.DateField(null=True, blank=True, verbose_name='成立日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '基金信息',
                'verbose_name_plural': '基金信息',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FundNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_date', models.DateField(db_index=True, verbose_name='净值日期')),
                ('unit_nav', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='单位净值')),
                ('accumulated_nav', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='累计净值')),
                ('daily_growth', models.DecimalField(decimal_places=4, max_digits=8, null=True, blank=True, verbose_name='日增长率')),
                ('estimated_nav', models.DecimalField(decimal_places=4, max_digits=10, null=True, blank=True, verbose_name='估算净值')),
                ('estimated_growth', models.DecimalField(decimal_places=4, max_digits=8, null=True, blank=True, verbose_name='估算增长率')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_records', to='funds.fund', verbose_name='基金')),
            ],
            options={
                'verbose_name': '基金净值记录',
                'verbose_name_plural': '基金净值记录',
                'ordering': ['-nav_date', '-updated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='fundnav',
            unique_together={('fund', 'nav_date')},
        ),
    ]
