# Generated by Django 4.2.7 on 2026-05-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['display_order', '-updated_at'], 'verbose_name': '基金信息', 'verbose_name_plural': '基金信息'},
        ),
        migrations.AddField(
            model_name='fund',
            name='display_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='显示排序'),
        ),
    ]
